config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: 'log_in'

  get "logout", to: "sessions#destroy"
  post "logout", to: "sessions#destroy" 

  get "profile", to: "users#profile"
  get "update-profile", to: "registrations#edit"
  patch "update-profile", to: "registrations#update"

  get "everyone", to: "users#everyone"

  resources :posts
  resources :comments
  resources :likes

  delete '/delete_like', :to => 'likes#delete_like'
  post '/liked', :to => 'likes#liked'


  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_presence_of :message
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: {
    scope: [ :user_id ],
    message: "A user can only like a post once"
  }

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates_presence_of :message #if :image_blank?
  #validates_presence_of :image_data #if :message_blank?
  #validates_presence_of :user_id 
  #validates_presence_of :message, :image_data if :both_present? 


=begin
  def invalid_post?
    message_blank? && image_blank?
  end

  def message_blank?
    message.blank?
  end

  def image_blank?
    image_data.blank?
  end
=end 

  #validate message unless image and message are both blank

  belongs_to :user
  has_many :likes
  has_many :comments
  #Should validate presence of text or image
end

app/models/user.rb
class User < ApplicationRecord
mount_uploader :photo, PhotoUploader
has_secure_password
  has_many :posts
  has_many :comments
  has_many :likes
validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Invalid email" }
validates_presence_of :first_name, :last_name, :date_of_birth
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in.." if Current.user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 

  def create 
  comment = Current.user.comments.new(post_params)
    if comment.save
      flash[:notice] = 'Comment was successfully created.'
      #redirect_to root_path
    else
      flash[:notice] = 'There was a problem.'
    end
  end

  private 

  def post_params
    params.require(:comment).permit(:message, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = Current.user.likes.create(post_params)
  end 

  def delete_like
    Like.destroy_by(post_params)
  end

  def liked
    Like.where(post_params)
  end 
  
  private 

  def post_params
    params.require(:like).permit(:post_id, :user_id)
  end    

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Current.user.posts.new(post_params)
    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to root_path
    else
      flash[:notice] = 'There was a problem.'
    end
  end

  def index
    @posts = Post.all
  end



  private

  def post_params
    params.require(:post).permit(:message, :photo, :post_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password, :email, :password_confirmation, :photo, :first_name, :last_name, :date_of_birth))

    session[:user_id] = @user.id
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account created!"
    else
      render :new
    end
  end

  def edit
    @current_user = Current.user
  end

  def update 
    if Current.user.update(first_name: params[:user][:first_name], last_name: params[:user][:last_name], email: params[:user][:email], date_of_birth: params[:user][:date_of_birth])
      redirect_to root_path, notice: "Account updated!"
    else
      render :edit
      flash[:notice] = "There was a problem updating your details. Try again."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Log In Success!"
    else
      flash.now[:alert] = "Invalid details."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = Current.user
    @posts = Current.user.posts.order("created_at DESC")
    @comment = Comment.new
    @likes = Like
  end

  def everyone
    @user = Current.user
    @users = User.all
  end

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # The welcome index view page renders many other pages (posts, profile etc)
    # The variables required from those pages need to be defined here

    @posts = Post.order("created_at DESC")
    @post = Post.new
    @comment = Comment.new 
    @likes = Like

    @user = Current.user
    @users = User.all

  end

end

app/helpers/application_helper.rb
require 'date'

module ApplicationHelper

  def format_birthday(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

  def id2name(user_id)
    user = User.find(user_id)
    user.first_name + "  " + user.last_name
  end

  def id2avatar(user_id)
    user = User.find(user_id)
    user.photo
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acebook</title>
    <%= csrf_meta_tags %>

   <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('branding/favicon.png') %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script>
   $(function() {
      $('.toast').toast('show');
   });
  </script>
  </body>
  
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <p><%= post.message %></p>
<% end %>

<%= link_to new_post_path do %>
  New post
<% end %>

app/views/posts/new.html.erb
<div class="d-flex w-100 justify-content-center">  
<div class="d-flex flex-column w-50 my-3">


<%= form_for @post do |f| %>
  <%= f.label :message %>
  <%= f.text_field :message %>

  <%= f.file_field :photo , :class => 'form-control', :type => 'file' %>

  <%= f.submit "Submit" %>
<% end %>

</div>
</div>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-expand-sm navbar-light bg-light" id="navbar">
   <div class="container-fluid">
     <a class="navbar-brand" id="navbar-logo-banner" href="/">acebook</a>
     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
       aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>
     <div class="nav navbar-right">
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <% if Current.user %>
         <a class="nav-link nav-user-name " href="<%= profile_path %>" id="profileLink" role="button">
            <%= image_tag(Current.user.photo.url, :style =>  'width: 35px;', :class => 'nav-avatar') if Current.user.photo? %>
            <%= Current.user.first_name%>
          </a>
           <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          </a>
          <ul class="pull-right dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= update_profile_path %>">Edit Profile</a></li>
            <li><a class="dropdown-item" href="<%= everyone_path %>">Find Friends</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= button_to 'Logout', logout_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
      </ul>  
    </ul>
    <li><%= link_to 'Logout', logout_path, class: 'btn nav-buttons btn-sm btn-outline-light' %></li>
         <% else %>
          <%= link_to 'Login', sign_in_path, class: 'btn nav-buttons btn-sm btn-outline-light' %>
         <%= link_to 'Sign Up', sign_up_path, class: 'btn nav-buttons btn-sm btn-outline-light' %>
         <% end %>
       </div>
     </div>
   </div>
 </nav>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute">
  <div class="d-flex">
    <div class="toast-body">
      <%= notice %>
   </div>
    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>
<% end %>
<% if alert %>
  <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute">
  <div class="d-flex">
    <div class="toast-body">
      <%= alert %>
   </div>
    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
  </div>
</div>
<% end %>

app/views/shared/_post_form.html.erb
<% if Current.user != nil %>

<div class="d-flex flex-column card my-2 p-1">
  <%= form_for @post do |f| %>
    <%= f.text_area :message, :id => "post-text-area", :placeholder => "What's on your mind?", :class => "form-control"%>
    <div class="d-flex flex-row justify-content-between">
      <a class="btn btn-primary m-1" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        <i class="bi bi-camera-fill"></i>
      </a>
      <%= f.submit "Post", :class => 'btn btn-primary btn-sm m-1'%>
    </div>
    <div class="collapse m-2" id="collapseExample">
      <%= f.file_field :photo , :class => 'form-control', :type => 'file' %>
    </div>
  <% end %>
</div>

<% end %>

app/views/shared/_posts.html.erb
<% if Current.user != nil %>
  <% @num = 1 %>
  <% @posts.each do |post| %>
    <div class="d-flex flex-column card my-2">
      <%# POST HEADERS %>
      <div class="d-flex flex-row  px-3 pt-3" id=header1>
        <img src="<%= id2avatar(post.user_id) %>" width="50" height="50" class="rounded-circle">
        <div class="d-flex flex-column mx-2">
          <h5 class="card-title"><%= id2name(post.user_id) %></h5>
          <p class="text-muted post-card-muted"><%= time_ago_in_words(post.created_at) %> ago</p>
        </div>
      </div>
      <%# POST MESSAGE %>
      <div class="card-body px-3">
        <p class="card-text"><%= "#{post.message}" %></p>
      </div>
      <%# POST IMAGE %>
      <% if post.photo %>
        <img src="<%= post.photo %>" class="img-fluid" >
      <% end %>
      <%# LIKE AND COMMENT BUTTONS %>
      <div class="class-body post-buttons py-1">
        <% liked = Current.user.likes.find_by(post_id: post.id) %>
        <% if liked == nil %>
          <button class="like-button post-action-buttons" id="likeButton" data-post_id="<%=post.id%>" >
            <input type="hidden" id="getUserID" value=" <%= Current.user.id %>">
            <i class="bi bi-hand-thumbs-up-fill" id="likeButtonStyling"></i>
          </button>
        <% else %>
          <button class="like-button post-action-buttons-liked" id="likeButton" data-post_id="<%=post.id%>" >
            <input type="hidden" id="getUserID" value=" <%= Current.user.id %>">
            <i class="bi bi-hand-thumbs-up-fill" id="likeButtonStyling"></i>
          </button>
        <% end %>
        <div id="<%=post.id%>">
          <% like_count = 0 %>
          <% (@likes.where(post_id: post.id)).each do |obj| %>
            <% like_count += 1 %>
          <% end %>
          <%=like_count%>
        </div>
        <button class="post-action-buttons" type="button" data-bs-toggle="collapse" data-bs-target="#<%= "collapseComment#{@num}"%>" aria-expanded="false" aria-controls="<%= "collapseComment#{@num}"%>">
          <i class="bi bi-chat-right-fill"></i>
        </button>
      </div>
      <%# NEW COMMENT FORM %>
      <div class="collapse" id="<%= "collapseComment#{@num}"%>">
      <div class="card-body d-flex flex-row p-2" id="makeANewComment">
        <%= image_tag(Current.user.photo.url, :style =>  'width: 45px', :style =>  'height: 45px', :class => 'nav-avatar') if Current.user.photo? %>
        <div class="d-flex flex-column w-100 mx-1">
          <input type="hidden" id="getFirstName" value="<%= Current.user.first_name %>">
          <input type="hidden" id="getLastName" value="<%= Current.user.last_name %>">
          <input type="hidden" id="getPostId" value="<%= post.id %>">
          <input type="string" class="w-100 form-control" id="commentContent" name="<%= post.id %>" >
          <p class="m-0"><small class="text-muted">Press enter to comment</small></p>
        </div>
      </div>
      </div>
    <%# SHOW COMMENTS ON THIS POST %>
    <div class=<%="postDiv#{post.id}"%>>
      <% post.comments.reverse.each do |comment| %>
        <div class="card-body d-flex flex-row py-1 px-1" >
          <img src="<%= id2avatar(comment.user_id) %>" width="35" height="35" class="rounded-circle" id="avatar" >
          <div>
            <div>
              <p class="post-comment-display mx-2 p-2">
                <% find_user_id = comment.user_id %>
                <% find_user = User.find_by(id: find_user_id) %>
                <small class="fw-bold comment-title card-text"><%= "#{find_user[:first_name]} #{find_user[:last_name]}" %> </small>
                <small class="comment-content card-text"><%= comment.message %></small>
              </p>
              <small class="text-muted card-text"><%= time_ago_in_words(comment.created_at) %> ago</small>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>

  <% @num += 1 %>
<% end %>
<% end %>
<script type="text/javascript">
  //Dynamic likes
  
  const devEnv = (<%= Rails.env.production? %>) ? 'https://hidden-everglades-40298.herokuapp.com/' : 'http://localhost:3000/'

  document.querySelectorAll("#likeButton").forEach(element => {
  
  element.addEventListener("click", ()=>{
    if (element.className == "like-button post-action-buttons"){
      console.log("i've been clicked an unliked button")
  
      let likeData = {"like" : {"post_id": element.getAttribute("data-post_id") }}
      fetch(`${devEnv}likes`, {
      method: "POST",
      headers: {
      "Content-Type" : "application/json",
    },
    body: JSON.stringify(likeData)
    })
    .then(() => {
    element.className = "like-button post-action-buttons-liked";
    let idNeeded = element.getAttribute("data-post_id")
    let count = document.getElementById(idNeeded)
    newCount = parseInt(count.innerText)
    count.innerText = `${newCount += 1}`
  })
  }
    else if (element.className == "like-button post-action-buttons-liked") {
      console.log("ive clicked a liked button")
    let getUserID = document.getElementById("getUserID")
    let deleteData = {"like" : {"post_id": element.getAttribute("data-post_id"), "user_id" : getUserID.value }}
    fetch(`${devEnv}delete_like/`, {
      method: "DELETE",
      headers: {
      "Content-Type" : "application/json",
    },
    body: JSON.stringify(deleteData)
  }).then(() => {
    element.className = "like-button post-action-buttons"
    let count = document.getElementById(element.getAttribute("data-post_id"))
    newCount = parseInt(count.innerText)
    count.innerText = `${newCount -= 1}`
  })
  }
  })
  })
  
  //Dynamic comments
  
  let getFirstName = document.getElementById("getFirstName")
  let getLastName = document.getElementById("getLastName")
  let userName = `${getFirstName.value} ${getLastName.value}`
  
  
   document.querySelectorAll("#commentContent").forEach(element => {
  
   element.addEventListener("keypress", (e) => {
     if(e.key == "Enter"){
      let data = {"comment": {"post_id": element.name, "message": element.value}}
      
      fetch(`${devEnv}comments`, {
      method: "POST",
      headers: {
        "Content-Type" : "application/json",
      },
      body: JSON.stringify(data)
    })
    .then(() => {
    let div2 = document.createElement("Div")
    let img = document.getElementById("avatar")
    let cloneImg = img.cloneNode(true)
    let div3 = document.createElement("Div")
    let p = document.createElement("p")
    p.className = "post-comment-display mx-2 p-2"
    let nameDisplay = document.createElement("small")
    nameDisplay.className = "fw-bold comment-title"
    nameDisplay.innerText = userName
    let contentDisplay = document.createElement("small")
    contentDisplay.className = "comment-content"
    contentDisplay.innerText = element.value
    p.appendChild(nameDisplay)
    p.appendChild(contentDisplay)
    div3.appendChild(p)
    let emptyDiv = document.createElement('div')
    emptyDiv.appendChild(div3)
    div2.appendChild(emptyDiv)
    let card = document.createElement("div")
    card.className = "card-body d-flex flex-row py-1 px-1"
    card.appendChild(cloneImg)
    card.appendChild(div2)
    let blah = document.querySelector(`.postDiv${element.name}`)
    blah.prepend(card)
    })
    .then(() =>{
      element.value = ""
    })
  }
   })
  })
</script>

app/views/shared/_welcome_page.html.erb
<div class="center">

<!-- left column, welcome image -->
  <div class="profile row">
    <div class="col-md-7 logo">
      <a class="navbar-brand" id="welcome-logo" href="/">acebook</a><br>
      <h3>Acebook helps you connect and share with the people in your life.</h3>
    </div>

<!-- right column, login form -->
  <div class="col-md-5 login_form"> 
            <main class="form-signin">
          <h1 class="h3 mb-3 fw-normal"> </h1>
        <%= form_with url: sign_in_path, local: true do |f| %>

          <div class="form-floating">
            <%= f.text_field :email, :class => 'form-control', :id => 'floatingEmail', :placeholder => 'user@example.com' %> 
            <label for="floatingEmail">Email address</label>
          </div>

          <div class="form-floating">
            <%= f.password_field :password, :class => 'form-control', :id => 'floatingPassword', :placeholder => 'Password' %>
            <label for="floatingPassword">Password</label>
          </div>

          <%= f.submit 'Sign In', :class => 'w-100 btn btn-lg btn-primary' %> 

          <hr/>
         <%= link_to 'Create New Account', sign_up_path, class: 'w-100 btn btn-lg btn-success' %>
          <% end %> 
          <p class="mt-3 mb-3">Create a page and join the community</p>
        </main>
  </div>
</div>

© 2021 JEAMM Team

app/views/users/_friend_panel.html.erb
<div class="container">
<div class="p-2 ">
    <h5> </h5>
  </div>
  <div class="p-2 ">
    <h5>Friend Suggestions:</h5>
  </div>
</div>

<div class="container">
  <div class="row g-3">

    <% @users.each do |user| %>
    <% if user != @user %>
      <div class="col-12" > 
      <div class="p-3 border"> 
      <div class="mt-3 text-center">
         <%= image_tag(user.photo.url, :style =>  'width: 90px; height: 90px;', :class => "rounded-circle") if user.photo?%> 
            <h5><%=user.first_name %> <%= user.last_name %></h5> 
            <button class="btn btn-primary btn-sm follow">Send request</button>
            <div class="d-flex justify-content-center align-items-center mt-4 px-4">
            <div class="stats">
              <h6 class="mb-0">Mutual friends</h6> <span>0</span>
            </div>
            </div>
      </div>
      </div>
      </div>
    <% end %>
    <% end %>

  </div>
</div>

app/views/users/_profile_panel.html.erb
<div class="mt-5 row align-items-start">
  <div class="col-12">
    <div class="container d-flex justify-content-center align-items-center" >
        <div class="card" id="profile-card">
            <div class="user text-center">
                <div class="profile mt-3"> <%= image_tag(Current.user.photo.url, :style =>  'width: 80px;', :class => "rounded-circle") if Current.user.photo? %> </div>
            </div>
            <div class="mt-3 text-center">
                <h4 class="mb-0"><%=Current.user.first_name %> <%= Current.user.last_name %></h4> <span class="text-muted d-block mb-2"><%= format_birthday(Current.user.date_of_birth) %></span> 
                <div class="d-flex justify-content-center align-items-center mt-4 px-4">
                    <div class="stats">
                        <h6 class="mb-0">Friends</h6> <span>0</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/users/everyone.html.erb
<div class="container">
  <div class="p-2 ">
    <h4>People you may know:</h4>
  </div>
</div>

<div class="container">
  <div class="row g-3">

    <% @users.each do |user| %>
    <% if user != @user %>  <!-- removes current user from friend suggestions -->
      <div class="col-3" > <!-- 4 cards in each row. the 'length' of a card is 3, 
      and the total BOOTSTRAP row length is 12.  Going over 12 it starts on the next row  -->
      <div class="p-3 border"> <!-- border for grid -->
      <div class="mt-3 text-center">
         <%= image_tag(user.photo.url, :style =>  'width: 90px;', :class => "rounded-circle") if user.photo?%> 
            <h5><%=user.first_name %> <%= user.last_name %></h5> 
            <button class="btn btn-primary btn-sm follow">Send request</button>
            <div class="d-flex justify-content-center align-items-center mt-4 px-4">
            <div class="stats">
              <h6 class="mb-0">Mutual friends</h6> <span>0</span>
            </div>
            </div>
      </div>
      </div>
      </div>
    <% end %>
    <% end %>

  </div>
</div>

<div class="container">
  <div class="p-2 ">
    <h4> </h4>
  </div>
</div>

<!-- card color is white -->
<style> 
    .p-3 {
        background-color: #ffffff;
        height: 350px;
    }
</style>

app/views/users/profile.html.erb
<div class="mt-5 row align-items-start">
  <div class="col-5">
    <div class="container d-flex justify-content-center align-items-center" >
        <div class="card" id="profile-card">
            <div class="user text-center">
                <div class="profile mt-3"> <%= image_tag(Current.user.photo.url, :style =>  'width: 80px;', :class => "rounded-circle") if Current.user.photo? %> </div>
            </div>
            <div class="mt-3 text-center">
                <h4 class="mb-0"><%=Current.user.first_name %> <%= Current.user.last_name %></h4> <span class="text-muted d-block mb-2"><%= format_birthday(Current.user.date_of_birth) %></span> 
                <div class="d-flex justify-content-center align-items-center mt-4 px-4">
                    <div class="stats">
                        <h6 class="mb-0">Friends</h6> <span>0</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div>
  <div class="col-4 bg-white">
  <%= render 'shared/posts' %>
  </div>
</div>

app/views/welcome/index.html.erb
<main>

  <div class="row justify-content-center"> <%# centers the 3 columns %>
  
    <div class="col-3"> <%# column 1: profile panel %>
      <% if Current.user.nil? %>
      <% else %>
       <%= render 'users/profile_panel' %>
      <% end %>
    </div>

    <div class="col-4"> <%# column 2: posts panel %>
    <% if Current.user.nil? %>
      <%= render 'shared/welcome_page' %>
    <% else %>
      <%= render 'shared/post_form' %>
      <%= render 'shared/posts' %>
    <% end %>
    </div>

    <div class="col-3"> <%# column 3: friend suggestions panel %>
      <% if Current.user.nil? %>
      <% else %>
       <%= render 'users/friend_panel' %>
      <% end %>
    </div>


  </div>
</main>